### ISSUE TITLE
Practica4 

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipowar#1]
https://drive.google.com/file/d/1DsgfYI8N2c7SqLJLJnwk49RyDArBDP9E/view?usp=sharing

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by HECTOR-KDM02** [comment]
20 Puntos 

Todas la rubricas se cumplieron perfectamente mejorar un poco su objetivo pero sin defectos en estos mismos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
